const WEAPONS = [
  {id:'clava',name:'Clava',damage:'1d6',type:'contundente',props:['leve'],ability:'for',range:'corpo a corpo'},
  {id:'adaga',name:'Adaga',damage:'1d4',type:'perfurante',props:['acuidade','leve','arremesso'],ability:'des',range:'corpo a corpo'},
  {id:'grande-clava',name:'Grande Clava',damage:'1d8',type:'contundente',props:['duas mãos'],ability:'for',range:'corpo a corpo'},
  {id:'machadinha',name:'Machadinha',damage:'1d6',type:'cortante',props:['leve','arremesso'],ability:'for',range:'corpo a corpo'},
  {id:'dardo',name:'Dardo',damage:'1d4',type:'perfurante',props:['acuidade','arremesso'],ability:'des',range:'distância'},
  {id:'azagaia',name:'Azagaia',damage:'1d6',type:'perfurante',props:['arremesso'],ability:'for',range:'distância'},
  {id:'maça',name:'Maça',damage:'1d6',type:'contundente',props:[],ability:'for',range:'corpo a corpo'},
  {id:'bordão',name:'Bordão',damage:'1d6',type:'contundente',props:['versátil'],ability:'for',range:'corpo a corpo'},
  {id:'foice',name:'Foice',damage:'1d4',type:'cortante',props:['leve'],ability:'for',range:'corpo a corpo'},
  {id:'funda',name:'Funda',damage:'1d4',type:'contundente',props:[],ability:'des',range:'distância'},
  {id:'martelo-leve',name:'Martelo Leve',damage:'1d4',type:'contundente',props:['leve','arremesso'],ability:'for',range:'corpo a corpo'},
  {id:'machado-batalha',name:'Machado de Batalha',damage:'1d8',type:'cortante',props:['versátil'],ability:'for',range:'corpo a corpo'},
  {id:'mangual',name:'Mangual',damage:'1d8',type:'contundente',props:[],ability:'for',range:'corpo a corpo'},
  {id:'rapieira',name:'Rapieira',damage:'1d8',type:'perfurante',props:['acuidade'],ability:'des',range:'corpo a corpo'},
  {id:'cimitarra',name:'Cimitarra',damage:'1d6',type:'cortante',props:['acuidade','leve'],ability:'des',range:'corpo a corpo'},
  {id:'espada-curta',name:'Espada Curta',damage:'1d6',type:'perfurante',props:['acuidade','leve'],ability:'des',range:'corpo a corpo'},
  {id:'machado-guerra',name:'Machado de Guerra',damage:'1d12',type:'cortante',props:['pesada','versátil'],ability:'for',range:'corpo a corpo'},
  {id:'espada-longa',name:'Espada Longa',damage:'1d8',type:'cortante',props:['versátil'],ability:'for',range:'corpo a corpo'},
  {id:'martelo-guerra',name:'Martelo de Guerra',damage:'1d8',type:'contundente',props:['versátil'],ability:'for',range:'corpo a corpo'},
  {id:'picareta-guerra',name:'Picareta de Guerra',damage:'1d8',type:'perfurante',props:[],ability:'for',range:'corpo a corpo'},
  {id:'alabarda',name:'Alabarda',damage:'1d10',type:'cortante',props:['pesada','alcance','duas mãos'],ability:'for',range:'corpo a corpo'},
  {id:'lança',name:'Lança',damage:'1d6',type:'perfurante',props:['arremesso','versátil'],ability:'for',range:'corpo a corpo'},
  {id:'espada-greatsword',name:'Espada Grande',damage:'2d6',type:'cortante',props:['pesada','duas mãos'],ability:'for',range:'corpo a corpo'},
  {id:'malho',name:'Malho',damage:'2d6',type:'contundente',props:['pesada','duas mãos'],ability:'for',range:'corpo a corpo'},
  {id:'montante',name:'Montante',damage:'1d10',type:'cortante',props:['pesada','alcance','duas mãos'],ability:'for',range:'corpo a corpo'},
  {id:'chicote',name:'Chicote',damage:'1d4',type:'cortante',props:['acuidade','alcance'],ability:'des',range:'corpo a corpo'},
  {id:'arco-curto',name:'Arco Curto',damage:'1d6',type:'perfurante',props:['duas mãos'],ability:'des',range:'distância'},
  {id:'besta-leve',name:'Besta Leve',damage:'1d8',type:'perfurante',props:['munição','duas mãos'],ability:'des',range:'distância'},
  {id:'arco-longo',name:'Arco Longo',damage:'1d8',type:'perfurante',props:['pesada','duas mãos'],ability:'des',range:'distância'},
  {id:'besta-mao',name:'Besta de Mão',damage:'1d6',type:'perfurante',props:['munição','leve'],ability:'des',range:'distância'},
  {id:'besta-pesada',name:'Besta Pesada',damage:'1d10',type:'perfurante',props:['pesada','duas mãos'],ability:'des',range:'distância'},
  {id:'glaive',name:'Glaive',damage:'1d10',type:'cortante',props:['pesada','alcance','duas mãos'],ability:'for',range:'corpo a corpo'},
  {id:'pistola',name:'Pistola',damage:'1d10',type:'perfurante',props:['munição'],ability:'des',range:'distância'},
  {id:'mosquete',name:'Mosquete',damage:'1d12',type:'perfurante',props:['munição','pesada','duas mãos'],ability:'des',range:'distância'},
  {id:'rede',name:'Rede',damage:'0',type:'especial',props:['arremesso'],ability:'des',range:'distância'},
  {id:'ataque-desarmado',name:'Ataque Desarmado',damage:'1 + FOR',type:'contundente',props:['natural'],ability:'for',range:'corpo a corpo'},
];

const ARMOR = [
  {id:'sem-armadura',name:'Sem armadura',base:0,dexCap:null,type:'nenhuma'},
  {id:'acolchoada',name:'Armadura acolchoada',base:11,dexCap:null,type:'leve'},
  {id:'couro',name:'Armadura de couro',base:11,dexCap:null,type:'leve'},
  {id:'couro-batido',name:'Couro batido',base:12,dexCap:null,type:'leve'},
  {id:'gibao-peles',name:'Gibão de peles',base:12,dexCap:2,type:'media'},
  {id:'camisa-malha',name:'Camisa de malha',base:13,dexCap:2,type:'media'},
  {id:'cota-escamas',name:'Cota de escamas',base:14,dexCap:2,type:'media'},
  {id:'cota-peitoral',name:'Cota peitoral',base:14,dexCap:2,type:'media'},
  {id:'meia-armadura',name:'Meia-armadura',base:15,dexCap:2,type:'media'},
  {id:'cota-aneis',name:'Cota de anéis',base:14,dexCap:0,type:'pesada'},
  {id:'cota-malha',name:'Cota de malha',base:16,dexCap:0,type:'pesada'},
  {id:'armadura-placas',name:'Armadura de placas',base:18,dexCap:0,type:'pesada'},
];

const SHIELD = {id:'escudo',name:'Escudo',ac:2};

const EQUIPMENT_THEMES = {
  havendor:{label:'Forja Radiante',material:'luz divina',damage:'radiante'},
  aurivelle:{label:'Madeira Encantada',material:'madeira viva e cordas',damage:'psíquico'},
  selah:{label:'Fluxo',material:'fibras naturais e energia',damage:'força'},
  ringendah:{label:'Arsenal Arcano',material:'runas e portais',damage:'energia'},
  knathi:{label:'Tinta Viva',material:'seiva e tinta',damage:'perfurante'},
  lumivior:{label:'Éter Tecnológico',material:'metal e circuitos',damage:'elétrico'},
  neruviah:{label:'Coral das Marés',material:'coral e água cristalizada',damage:'gelo'},
  argolis:{label:'Aço Tático',material:'aço e mecanismos',damage:'cortante'},
  sphalidor:{label:'Aço Ressonante',material:'cristal e metal vibrante',damage:'sônico'},
};
