const ALL_SPELLS = [
  {id:'respingo-cido',n:'Respingo Ácido',o:'Acid Splash',c:0,s:'Evocação',m:0,cal:0},
  {id:'toque-glido',n:'Toque Gélido',o:'Chill Touch',c:0,s:'Necromancia',m:0,cal:0},
  {id:'luzes-danantes',n:'Luzes Dançantes',o:'Dancing Lights',c:0,s:'Ilusão',m:0,cal:0},
  {id:'druidismo',n:'Druidismo',o:'Druidcraft',c:0,s:'Transmutação',m:0,cal:0},
  {id:'rajada-mstica',n:'Rajada Mística',o:'Eldritch Blast',c:0,s:'Evocação',m:0,cal:0},
  {id:'elementalismo',n:'Elementalismo',o:'Elementalism',c:0,s:'Transmutação',m:0,cal:0},
  {id:'raio-de-fogo',n:'Raio de Fogo',o:'Fire Bolt',c:0,s:'Evocação',m:0,cal:0},
  {id:'orientao',n:'Orientação',o:'Guidance',c:0,s:'Adivinhação',m:0,cal:0},
  {id:'luz',n:'Luz',o:'Light',c:0,s:'Evocação',m:0,cal:0},
  {id:'mo-mgica',n:'Mão Mágica',o:'Mage Hand',c:0,s:'Conjuração',m:0,cal:0},
  {id:'reparo',n:'Reparo',o:'Mending',c:0,s:'Transmutação',m:0,cal:0},
  {id:'mensagem',n:'Mensagem',o:'Message',c:0,s:'Transmutação',m:0,cal:0},
  {id:'iluso-menor',n:'Ilusão Menor',o:'Minor Illusion',c:0,s:'Ilusão',m:0,cal:0},
  {id:'spray-venenoso',n:'Spray Venenoso',o:'Poison Spray',c:0,s:'Necromancia',m:0,cal:0},
  {id:'prestidigitao',n:'Prestidigitação',o:'Prestidigitation',c:0,s:'Transmutação',m:0,cal:0},
  {id:'produzir-chama',n:'Produzir Chama',o:'Produce Flame',c:0,s:'Conjuração',m:0,cal:0},
  {id:'raio-de-gelo',n:'Raio de Gelo',o:'Ray of Frost',c:0,s:'Evocação',m:0,cal:0},
  {id:'resistncia',n:'Resistência',o:'Resistance',c:0,s:'Abjuração',m:0,cal:0},
  {id:'chama-sagrada',n:'Chama Sagrada',o:'Sacred Flame',c:0,s:'Evocação',m:0,cal:0},
  {id:'chibata',n:'Chibata',o:'Shillelagh',c:0,s:'Transmutação',m:0,cal:0},
  {id:'golpe-chocante',n:'Golpe Chocante',o:'Shocking Grasp',c:0,s:'Evocação',m:0,cal:0},
  {id:'sorcerous-burst',n:'Sorcerous Burst',o:'Sorcerous Burst',c:0,s:'Evocação',m:0,cal:0},
  {id:'prolongar-vida',n:'Prolongar Vida',o:'Spare the Dying',c:0,s:'Necromancia',m:0,cal:0},
  {id:'starry-wisp',n:'Starry Wisp',o:'Starry Wisp',c:0,s:'Evocação',m:0,cal:0},
  {id:'taumaturgia',n:'Taumaturgia',o:'Thaumaturgy',c:0,s:'Transmutação',m:0,cal:0},
  {id:'golpe-verdadeiro',n:'Golpe Verdadeiro',o:'True Strike',c:0,s:'Adivinhação',m:0,cal:0},
  {id:'escrnio-cruel',n:'Escárnio Cruel',o:'Vicious Mockery',c:0,s:'Encantamento',m:0,cal:0},
  {id:'alarme',n:'Alarme',o:'Alarm',c:1,s:'Abjuração',m:5,cal:1},
  {id:'amizade-animal',n:'Amizade Animal',o:'Animal Friendship',c:1,s:'Encantamento',m:5,cal:1},
  {id:'maldio',n:'Maldição',o:'Bane',c:1,s:'Encantamento',m:5,cal:1},
  {id:'bno',n:'Bênção',o:'Bless',c:1,s:'Encantamento',m:5,cal:1},
  {id:'mos-flamejantes',n:'Mãos Flamejantes',o:'Burning Hands',c:1,s:'Evocação',m:5,cal:1},
  {id:'encantar-pessoa',n:'Encantar Pessoa',o:'Charm Person',c:1,s:'Encantamento',m:5,cal:1},
  {id:'chromatic-orb',n:'Chromatic Orb',o:'Chromatic Orb',c:1,s:'Evocação',m:5,cal:1},
  {id:'jato-de-cores',n:'Jato de Cores',o:'Color Spray',c:1,s:'Ilusão',m:5,cal:1},
  {id:'comando',n:'Comando',o:'Command',c:1,s:'Encantamento',m:5,cal:1},
  {id:'compreender-idiomas',n:'Compreender Idiomas',o:'Comprehend Languages',c:1,s:'Adivinhação',m:5,cal:1},
  {id:'criar-ou-destruir-gua',n:'Criar ou Destruir Água',o:'Create or Destroy Water',c:1,s:'Transmutação',m:5,cal:1},
  {id:'cura-ferimentos',n:'Cura Ferimentos',o:'Cure Wounds',c:1,s:'Abjuração',m:5,cal:1},
  {id:'detectar-o-bem-e-o-mal',n:'Detectar o Bem e o Mal',o:'Detect Evil and Good',c:1,s:'Adivinhação',m:5,cal:1},
  {id:'detectar-magia',n:'Detectar Magia',o:'Detect Magic',c:1,s:'Adivinhação',m:5,cal:1},
  {id:'detectar-veneno-e-doena',n:'Detectar Veneno e Doença',o:'Detect Poison and Disease',c:1,s:'Adivinhação',m:5,cal:1},
  {id:'disfararse',n:'Disfarçar-se',o:'Disguise Self',c:1,s:'Ilusão',m:5,cal:1},
  {id:'dissonant-whispers',n:'Dissonant Whispers',o:'Dissonant Whispers',c:1,s:'Encantamento',m:5,cal:1},
  {id:'favor-divino',n:'Favor Divino',o:'Divine Favor',c:1,s:'Transmutação',m:5,cal:1},
  {id:'divine-smite',n:'Divine Smite',o:'Divine Smite',c:1,s:'Evocação',m:5,cal:1},
  {id:'ensnaring-strike',n:'Ensnaring Strike',o:'Ensnaring Strike',c:1,s:'Conjuração',m:5,cal:1},
  {id:'enredar',n:'Enredar',o:'Entangle',c:1,s:'Conjuração',m:5,cal:1},
  {id:'retirada-rpida',n:'Retirada Rápida',o:'Expeditious Retreat',c:1,s:'Transmutação',m:5,cal:1},
  {id:'fogo-frico',n:'Fogo Fáérico',o:'Faerie Fire',c:1,s:'Evocação',m:5,cal:1},
  {id:'vida-falsa',n:'Vida Falsa',o:'False Life',c:1,s:'Necromancia',m:5,cal:1},
  {id:'queda-de-pena',n:'Queda de Pena',o:'Feather Fall',c:1,s:'Transmutação',m:5,cal:1},
  {id:'encontrar-familiar',n:'Encontrar Familiar',o:'Find Familiar',c:1,s:'Conjuração',m:5,cal:1},
  {id:'floating-disk',n:'Floating Disk',o:'Floating Disk',c:1,s:'Conjuração',m:5,cal:1},
  {id:'nuvem-de-nvoa',n:'Nuvem de Névoa',o:'Fog Cloud',c:1,s:'Conjuração',m:5,cal:1},
  {id:'fruta-boa',n:'Fruta Boa',o:'Goodberry',c:1,s:'Conjuração',m:5,cal:1},
  {id:'graxa',n:'Graxa',o:'Grease',c:1,s:'Conjuração',m:5,cal:1},
  {id:'raio-guiado',n:'Raio Guiado',o:'Guiding Bolt',c:1,s:'Evocação',m:5,cal:1},
  {id:'palavra-de-cura',n:'Palavra de Cura',o:'Healing Word',c:1,s:'Abjuração',m:5,cal:1},
  {id:'repreenso-infernal',n:'Repreensão Infernal',o:'Hellish Rebuke',c:1,s:'Evocação',m:5,cal:1},
  {id:'herosmo',n:'Heroísmo',o:'Heroism',c:1,s:'Encantamento',m:5,cal:1},
  {id:'hex',n:'Hex',o:'Hex',c:1,s:'Encantamento',m:5,cal:1},
  {id:'risada-horrvel',n:'Risada Horrível',o:'Hideous Laughter',c:1,s:'Encantamento',m:5,cal:1},
  {id:'marca-do-caador',n:'Marca do Caçador',o:'Hunter\'s Mark',c:1,s:'Adivinhação',m:5,cal:1},
  {id:'ice-knife',n:'Ice Knife',o:'Ice Knife',c:1,s:'Conjuração',m:5,cal:1},
  {id:'identificar',n:'Identificar',o:'Identify',c:1,s:'Adivinhação',m:5,cal:1},
  {id:'escrita-ilusria',n:'Escrita Ilusória',o:'Illusory Script',c:1,s:'Ilusão',m:5,cal:1},
  {id:'causar-ferimentos',n:'Causar Ferimentos',o:'Inflict Wounds',c:1,s:'Necromancia',m:5,cal:1},
  {id:'saltar',n:'Saltar',o:'Jump',c:1,s:'Transmutação',m:5,cal:1},
  {id:'passos-longos',n:'Passos Longos',o:'Longstrider',c:1,s:'Transmutação',m:5,cal:1},
  {id:'armadura-arcana',n:'Armadura Arcana',o:'Mage Armor',c:1,s:'Abjuração',m:5,cal:1},
  {id:'mssil-mgico',n:'Míssil Mágico',o:'Magic Missile',c:1,s:'Evocação',m:5,cal:1},
  {id:'proteo-contra-o-bem-e-o-mal',n:'Proteção contra o Bem e o Mal',o:'Protection from Evil and Good',c:1,s:'Abjuração',m:5,cal:1},
  {id:'purificar-comida-e-bebida',n:'Purificar Comida e Bebida',o:'Purify Food and Drink',c:1,s:'Transmutação',m:5,cal:1},
  {id:'raio-de-doena',n:'Raio de Doença',o:'Ray of Sickness',c:1,s:'Necromancia',m:5,cal:1},
  {id:'santurio',n:'Santuário',o:'Sanctuary',c:1,s:'Abjuração',m:5,cal:1},
  {id:'golpe-flamejante',n:'Golpe Flamejante',o:'Searing Smite',c:1,s:'Evocação',m:5,cal:1},
  {id:'escudo',n:'Escudo',o:'Shield',c:1,s:'Abjuração',m:5,cal:1},
  {id:'escudo-da-f',n:'Escudo da Fé',o:'Shield of Faith',c:1,s:'Abjuração',m:5,cal:1},
  {id:'imagem-silenciosa',n:'Imagem Silenciosa',o:'Silent Image',c:1,s:'Ilusão',m:5,cal:1},
  {id:'sono',n:'Sono',o:'Sleep',c:1,s:'Encantamento',m:5,cal:1},
  {id:'falar-com-animais',n:'Falar com Animais',o:'Speak with Animals',c:1,s:'Adivinhação',m:5,cal:1},
  {id:'onda-trovo',n:'Onda Trovão',o:'Thunderwave',c:1,s:'Evocação',m:5,cal:1},
  {id:'servo-invisvel',n:'Servo Invisível',o:'Unseen Servant',c:1,s:'Conjuração',m:5,cal:1},
  {id:'flecha-cida',n:'Flecha Ácida',o:'Acid Arrow',c:2,s:'Evocação',m:10,cal:2},
  {id:'auxlio',n:'Auxílio',o:'Aid',c:2,s:'Abjuração',m:10,cal:2},
  {id:'alterar-autoconscincia',n:'Alterar Autoconsciência',o:'Alter Self',c:2,s:'Transmutação',m:10,cal:2},
  {id:'mensageiro-animal',n:'Mensageiro Animal',o:'Animal Messenger',c:2,s:'Encantamento',m:10,cal:2},
  {id:'fechadura-arcana',n:'Fechadura Arcana',o:'Arcane Lock',c:2,s:'Abjuração',m:10,cal:2},
  {id:'aura-mgica-do-arcanista',n:'Aura Mágica do Arcanista',o:'Arcanist\'s Magic Aura',c:2,s:'Ilusão',m:10,cal:2},
  {id:'augrio',n:'Augúrio',o:'Augury',c:2,s:'Adivinhação',m:10,cal:2},
  {id:'pele-de-casca',n:'Pele de Casca',o:'Barkskin',c:2,s:'Transmutação',m:10,cal:2},
  {id:'cegueirasurdez',n:'Cegueira/Surdez',o:'Blindness/Deafness',c:2,s:'Transmutação',m:10,cal:2},
  {id:'borrifo',n:'Borrifo',o:'Blur',c:2,s:'Ilusão',m:10,cal:2},
  {id:'aquietar-emoes',n:'Aquietar Emoções',o:'Calm Emotions',c:2,s:'Encantamento',m:10,cal:2},
  {id:'chama-contnua',n:'Chama Contínua',o:'Continual Flame',c:2,s:'Evocação',m:10,cal:2},
  {id:'escurido',n:'Escuridão',o:'Darkness',c:2,s:'Evocação',m:10,cal:2},
  {id:'viso-no-escuro',n:'Visão no Escuro',o:'Darkvision',c:2,s:'Transmutação',m:10,cal:2},
  {id:'detectar-pensamentos',n:'Detectar Pensamentos',o:'Detect Thoughts',c:2,s:'Adivinhação',m:10,cal:2},
  {id:'dragons-breath',n:'Dragon\'s Breath',o:'Dragon\'s Breath',c:2,s:'Transmutação',m:10,cal:2},
  {id:'aprimorar-atributo',n:'Aprimorar Atributo',o:'Enhance Ability',c:2,s:'Transmutação',m:10,cal:2},
  {id:'aumentarreduzir',n:'Aumentar/Reduzir',o:'Enlarge/Reduce',c:2,s:'Transmutação',m:10,cal:2},
  {id:'cativar',n:'Cativar',o:'Enthrall',c:2,s:'Encantamento',m:10,cal:2},
  {id:'encontrar-montaria',n:'Encontrar Montaria',o:'Find Steed',c:2,s:'Conjuração',m:10,cal:2},
  {id:'encontrar-armadilhas',n:'Encontrar Armadilhas',o:'Find Traps',c:2,s:'Adivinhação',m:10,cal:2},
  {id:'lmina-flamejante',n:'Lâmina Flamejante',o:'Flame Blade',c:2,s:'Evocação',m:10,cal:2},
  {id:'esfera-flamejante',n:'Esfera Flamejante',o:'Flaming Sphere',c:2,s:'Conjuração',m:10,cal:2},
  {id:'repouso-tranquilo',n:'Repouso Tranquilo',o:'Gentle Repose',c:2,s:'Necromancia',m:10,cal:2},
  {id:'rajada-de-vento',n:'Rajada de Vento',o:'Gust of Wind',c:2,s:'Evocação',m:10,cal:2},
  {id:'aquecer-metal',n:'Aquecer Metal',o:'Heat Metal',c:2,s:'Transmutação',m:10,cal:2},
  {id:'imobilizar-pessoa',n:'Imobilizar Pessoa',o:'Hold Person',c:2,s:'Encantamento',m:10,cal:2},
  {id:'invisibilidade',n:'Invisibilidade',o:'Invisibility',c:2,s:'Ilusão',m:10,cal:2},
  {id:'arrombar',n:'Arrombar',o:'Knock',c:2,s:'Transmutação',m:10,cal:2},
  {id:'restaurao-menor',n:'Restauração Menor',o:'Lesser Restoration',c:2,s:'Abjuração',m:10,cal:2},
  {id:'levitao',n:'Levitação',o:'Levitate',c:2,s:'Transmutação',m:10,cal:2},
  {id:'localizar-animais-ou-plantas',n:'Localizar Animais ou Plantas',o:'Locate Animals or Plants',c:2,s:'Adivinhação',m:10,cal:2},
  {id:'localizar-objeto',n:'Localizar Objeto',o:'Locate Object',c:2,s:'Adivinhação',m:10,cal:2},
  {id:'boca-mgica',n:'Boca Mágica',o:'Magic Mouth',c:2,s:'Ilusão',m:10,cal:2},
  {id:'arma-mgica',n:'Arma Mágica',o:'Magic Weapon',c:2,s:'Transmutação',m:10,cal:2},
  {id:'mind-spike',n:'Mind Spike',o:'Mind Spike',c:2,s:'Adivinhação',m:10,cal:2},
  {id:'imagem-espelhada',n:'Imagem Espelhada',o:'Mirror Image',c:2,s:'Ilusão',m:10,cal:2},
  {id:'passo-nebuloso',n:'Passo Nebuloso',o:'Misty Step',c:2,s:'Conjuração',m:10,cal:2},
  {id:'raio-lunar',n:'Raio Lunar',o:'Moonbeam',c:2,s:'Evocação',m:10,cal:2},
  {id:'passo-sem-pegadas',n:'Passo sem Pegadas',o:'Pass without Trace',c:2,s:'Abjuração',m:10,cal:2},
  {id:'phantasmal-force',n:'Phantasmal Force',o:'Phantasmal Force',c:2,s:'Ilusão',m:10,cal:2},
  {id:'prece-de-cura',n:'Prece de Cura',o:'Prayer of Healing',c:2,s:'Abjuração',m:10,cal:2},
  {id:'proteo-contra-veneno',n:'Proteção contra Veneno',o:'Protection from Poison',c:2,s:'Abjuração',m:10,cal:2},
  {id:'raio-de-enfraquecimento',n:'Raio de Enfraquecimento',o:'Ray of Enfeeblement',c:2,s:'Necromancia',m:10,cal:2},
  {id:'truque-da-corda',n:'Truque da Corda',o:'Rope Trick',c:2,s:'Transmutação',m:10,cal:2},
  {id:'raio-escaldante',n:'Raio Escaldante',o:'Scorching Ray',c:2,s:'Evocação',m:10,cal:2},
  {id:'ver-invisibilidade',n:'Ver Invisibilidade',o:'See Invisibility',c:2,s:'Adivinhação',m:10,cal:2},
  {id:'estilhaar',n:'Estilhaçar',o:'Shatter',c:2,s:'Evocação',m:10,cal:2},
  {id:'shining-smite',n:'Shining Smite',o:'Shining Smite',c:2,s:'Transmutação',m:10,cal:2},
  {id:'silncio',n:'Silêncio',o:'Silence',c:2,s:'Ilusão',m:10,cal:2},
  {id:'escalar-como-aranha',n:'Escalar como Aranha',o:'Spider Climb',c:2,s:'Transmutação',m:10,cal:2},
  {id:'crescimento-de-espinhos',n:'Crescimento de Espinhos',o:'Spike Growth',c:2,s:'Transmutação',m:10,cal:2},
  {id:'arma-espiritual',n:'Arma Espiritual',o:'Spiritual Weapon',c:2,s:'Evocação',m:10,cal:2},
  {id:'sugesto',n:'Sugestão',o:'Suggestion',c:2,s:'Encantamento',m:10,cal:2},
  {id:'vnculo-protetor',n:'Vínculo Protetor',o:'Warding Bond',c:2,s:'Abjuração',m:10,cal:2},
  {id:'teia',n:'Teia',o:'Web',c:2,s:'Conjuração',m:10,cal:2},
  {id:'zona-da-verdade',n:'Zona da Verdade',o:'Zone of Truth',c:2,s:'Encantamento',m:10,cal:2},
  {id:'animao-de-mortos',n:'Animação de Mortos',o:'Animate Dead',c:3,s:'Necromancia',m:15,cal:3},
  {id:'farol-de-esperana',n:'Farol de Esperança',o:'Beacon of Hope',c:3,s:'Abjuração',m:15,cal:3},
  {id:'impor-maldio',n:'Impor Maldição',o:'Bestow Curse',c:3,s:'Necromancia',m:15,cal:3},
  {id:'piscar',n:'Piscar',o:'Blink',c:3,s:'Transmutação',m:15,cal:3},
  {id:'convocar-relmpago',n:'Convocar Relâmpago',o:'Call Lightning',c:3,s:'Conjuração',m:15,cal:3},
  {id:'clarividncia',n:'Clarividência',o:'Clairvoyance',c:3,s:'Adivinhação',m:15,cal:3},
  {id:'conjurar-animais',n:'Conjurar Animais',o:'Conjure Animals',c:3,s:'Conjuração',m:15,cal:3},
  {id:'contramgica',n:'Contramágica',o:'Counterspell',c:3,s:'Abjuração',m:15,cal:3},
  {id:'criar-comida-e-gua',n:'Criar Comida e Água',o:'Create Food and Water',c:3,s:'Conjuração',m:15,cal:3},
  {id:'luz-do-dia',n:'Luz do Dia',o:'Daylight',c:3,s:'Evocação',m:15,cal:3},
  {id:'dissipar-magia',n:'Dissipar Magia',o:'Dispel Magic',c:3,s:'Abjuração',m:15,cal:3},
  {id:'medo',n:'Medo',o:'Fear',c:3,s:'Ilusão',m:15,cal:3},
  {id:'bola-de-fogo',n:'Bola de Fogo',o:'Fireball',c:3,s:'Evocação',m:15,cal:3},
  {id:'voar',n:'Voar',o:'Fly',c:3,s:'Transmutação',m:15,cal:3},
  {id:'forma-gasosa',n:'Forma Gasosa',o:'Gaseous Form',c:3,s:'Transmutação',m:15,cal:3},
  {id:'glifo-de-proteo',n:'Glifo de Proteção',o:'Glyph of Warding',c:3,s:'Abjuração',m:15,cal:3},
  {id:'acelerao',n:'Aceleração',o:'Haste',c:3,s:'Transmutação',m:15,cal:3},
  {id:'padro-hipntico',n:'Padrão Hipnótico',o:'Hypnotic Pattern',c:3,s:'Ilusão',m:15,cal:3},
  {id:'raio',n:'Raio',o:'Lightning Bolt',c:3,s:'Evocação',m:15,cal:3},
  {id:'crculo-mgico',n:'Círculo Mágico',o:'Magic Circle',c:3,s:'Abjuração',m:15,cal:3},
  {id:'imagem-maior',n:'Imagem Maior',o:'Major Image',c:3,s:'Ilusão',m:15,cal:3},
  {id:'palavra-de-cura-em-massa',n:'Palavra de Cura em Massa',o:'Mass Healing Word',c:3,s:'Abjuração',m:15,cal:3},
  {id:'fundirse--pedra',n:'Fundir-se à Pedra',o:'Meld into Stone',c:3,s:'Transmutação',m:15,cal:3},
  {id:'no-deteco',n:'Não Detecção',o:'Nondetection',c:3,s:'Abjuração',m:15,cal:3},
  {id:'montaria-fantasma',n:'Montaria Fantasma',o:'Phantom Steed',c:3,s:'Ilusão',m:15,cal:3},
  {id:'plant-growth',n:'Plant Growth',o:'Plant Growth',c:3,s:'Transmutação',m:15,cal:3},
  {id:'proteo-contra-energia',n:'Proteção contra Energia',o:'Protection from Energy',c:3,s:'Abjuração',m:15,cal:3},
  {id:'remover-maldio',n:'Remover Maldição',o:'Remove Curse',c:3,s:'Abjuração',m:15,cal:3},
  {id:'revificao',n:'Revificação',o:'Revivify',c:3,s:'Necromancia',m:15,cal:3},
  {id:'envio',n:'Envio',o:'Sending',c:3,s:'Adivinhação',m:15,cal:3},
  {id:'tempestade-de-neve',n:'Tempestade de Neve',o:'Sleet Storm',c:3,s:'Conjuração',m:15,cal:3},
  {id:'lentido',n:'Lentidão',o:'Slow',c:3,s:'Transmutação',m:15,cal:3},
  {id:'falar-com-mortos',n:'Falar com Mortos',o:'Speak with Dead',c:3,s:'Necromancia',m:15,cal:3},
  {id:'falar-com-plantas',n:'Falar com Plantas',o:'Speak with Plants',c:3,s:'Transmutação',m:15,cal:3},
  {id:'guardies-espirituais',n:'Guardiões Espirituais',o:'Spirit Guardians',c:3,s:'Conjuração',m:15,cal:3},
  {id:'nuvem-ftida',n:'Nuvem Fétida',o:'Stinking Cloud',c:3,s:'Conjuração',m:15,cal:3},
  {id:'tiny-hut',n:'Tiny Hut',o:'Tiny Hut',c:3,s:'Evocação',m:15,cal:3},
  {id:'idiomas',n:'Idiomas',o:'Tongues',c:3,s:'Adivinhação',m:15,cal:3},
  {id:'toque-vamprico',n:'Toque Vampírico',o:'Vampiric Touch',c:3,s:'Necromancia',m:15,cal:3},
  {id:'respirar-na-gua',n:'Respirar na Água',o:'Water Breathing',c:3,s:'Transmutação',m:15,cal:3},
  {id:'andar-na-gua',n:'Andar na Água',o:'Water Walk',c:3,s:'Transmutação',m:15,cal:3},
  {id:'muralha-de-vento',n:'Muralha de Vento',o:'Wind Wall',c:3,s:'Evocação',m:15,cal:3},
  {id:'olho-arcano',n:'Olho Arcano',o:'Arcane Eye',c:4,s:'Adivinhação',m:20,cal:4},
  {id:'aura-de-vida',n:'Aura de Vida',o:'Aura of Life',c:4,s:'Abjuração',m:20,cal:4},
  {id:'banimento',n:'Banimento',o:'Banishment',c:4,s:'Abjuração',m:20,cal:4},
  {id:'tentculos-negros',n:'Tentáculos Negros',o:'Black Tentacles',c:4,s:'Conjuração',m:20,cal:4},
  {id:'praga',n:'Praga',o:'Blight',c:4,s:'Necromancia',m:20,cal:4},
  {id:'charm-monster',n:'Charm Monster',o:'Charm Monster',c:4,s:'Encantamento',m:20,cal:4},
  {id:'compulso',n:'Compulsão',o:'Compulsion',c:4,s:'Encantamento',m:20,cal:4},
  {id:'confusion',n:'Confusion',o:'Confusion',c:4,s:'Encantamento',m:20,cal:4},
  {id:'conjurar-elementais-menores',n:'Conjurar Elementais Menores',o:'Conjure Minor Elementals',c:4,s:'Conjuração',m:20,cal:4},
  {id:'conjurar-seres-da-floresta',n:'Conjurar Seres da Floresta',o:'Conjure Woodland Beings',c:4,s:'Conjuração',m:20,cal:4},
  {id:'controlar-gua',n:'Controlar Água',o:'Control Water',c:4,s:'Transmutação',m:20,cal:4},
  {id:'proteo-contra-a-morte',n:'Proteção contra a Morte',o:'Death Ward',c:4,s:'Abjuração',m:20,cal:4},
  {id:'porta-dimensional',n:'Porta Dimensional',o:'Dimension Door',c:4,s:'Conjuração',m:20,cal:4},
  {id:'adivinhao',n:'Adivinhação',o:'Divination',c:4,s:'Adivinhação',m:20,cal:4},
  {id:'dominar-besta',n:'Dominar Besta',o:'Dominate Beast',c:4,s:'Encantamento',m:20,cal:4},
  {id:'fabricar',n:'Fabricar',o:'Fabricate',c:4,s:'Transmutação',m:20,cal:4},
  {id:'co-fiel',n:'Cão Fiel',o:'Faithful Hound',c:4,s:'Conjuração',m:20,cal:4},
  {id:'escudo-de-fogo',n:'Escudo de Fogo',o:'Fire Shield',c:4,s:'Evocação',m:20,cal:4},
  {id:'liberdade-de-movimento',n:'Liberdade de Movimento',o:'Freedom of Movement',c:4,s:'Abjuração',m:20,cal:4},
  {id:'inseto-gigante',n:'Inseto Gigante',o:'Giant Insect',c:4,s:'Conjuração',m:20,cal:4},
  {id:'invisibilidade-superior',n:'Invisibilidade Superior',o:'Greater Invisibility',c:4,s:'Ilusão',m:20,cal:4},
  {id:'guardio-da-f',n:'Guardião da Fé',o:'Guardian of Faith',c:4,s:'Conjuração',m:20,cal:4},
  {id:'terreno-alucinatrio',n:'Terreno Alucinatório',o:'Hallucinatory Terrain',c:4,s:'Ilusão',m:20,cal:4},
  {id:'tempestade-de-gelo',n:'Tempestade de Gelo',o:'Ice Storm',c:4,s:'Evocação',m:20,cal:4},
  {id:'localizar-criatura',n:'Localizar Criatura',o:'Locate Creature',c:4,s:'Adivinhação',m:20,cal:4},
  {id:'assassino-fantasma',n:'Assassino Fantasma',o:'Phantasmal Killer',c:4,s:'Ilusão',m:20,cal:4},
  {id:'polimorfia',n:'Polimorfia',o:'Polymorph',c:4,s:'Transmutação',m:20,cal:4},
  {id:'private-sanctum',n:'Private Sanctum',o:'Private Sanctum',c:4,s:'Abjuração',m:20,cal:4},
  {id:'resilient-sphere',n:'Resilient Sphere',o:'Resilient Sphere',c:4,s:'Evocação',m:20,cal:4},
  {id:'secret-chest',n:'Secret Chest',o:'Secret Chest',c:4,s:'Conjuração',m:20,cal:4},
  {id:'moldar-pedra',n:'Moldar Pedra',o:'Stone Shape',c:4,s:'Transmutação',m:20,cal:4},
  {id:'pele-de-pedra',n:'Pele de Pedra',o:'Stoneskin',c:4,s:'Transmutação',m:20,cal:4},
  {id:'vitriolic-sphere',n:'Vitriolic Sphere',o:'Vitriolic Sphere',c:4,s:'Evocação',m:20,cal:4},
  {id:'muralha-de-fogo',n:'Muralha de Fogo',o:'Wall of Fire',c:4,s:'Evocação',m:20,cal:4},
  {id:'animao-de-objetos',n:'Animação de Objetos',o:'Animate Objects',c:5,s:'Transmutação',m:25,cal:5},
  {id:'barreira-antivida',n:'Barreira Antivida',o:'Antilife Shell',c:5,s:'Abjuração',m:25,cal:5},
  {id:'mo-arcanssima',n:'Mão Arcaníssima',o:'Arcane Hand',c:5,s:'Evocação',m:25,cal:5},
  {id:'despertar',n:'Despertar',o:'Awaken',c:5,s:'Transmutação',m:25,cal:5},
  {id:'nuvem-mortal',n:'Nuvem Mortal',o:'Cloudkill',c:5,s:'Conjuração',m:25,cal:5},
  {id:'comunho',n:'Comunhão',o:'Commune',c:5,s:'Adivinhação',m:25,cal:5},
  {id:'comunho-com-a-natureza',n:'Comunhão com a Natureza',o:'Commune with Nature',c:5,s:'Adivinhação',m:25,cal:5},
  {id:'cone-de-frio',n:'Cone de Frio',o:'Cone of Cold',c:5,s:'Evocação',m:25,cal:5},
  {id:'conjurar-elemental',n:'Conjurar Elemental',o:'Conjure Elemental',c:5,s:'Conjuração',m:25,cal:5},
  {id:'contatar-outro-plano',n:'Contatar Outro Plano',o:'Contact Other Plane',c:5,s:'Adivinhação',m:25,cal:5},
  {id:'contgio',n:'Contágio',o:'Contagion',c:5,s:'Necromancia',m:25,cal:5},
  {id:'criao',n:'Criação',o:'Creation',c:5,s:'Ilusão',m:25,cal:5},
  {id:'dissipar-o-bem-e-o-mal',n:'Dissipar o Bem e o Mal',o:'Dispel Evil and Good',c:5,s:'Abjuração',m:25,cal:5},
  {id:'dominar-pessoa',n:'Dominar Pessoa',o:'Dominate Person',c:5,s:'Encantamento',m:25,cal:5},
  {id:'sonho',n:'Sonho',o:'Dream',c:5,s:'Ilusão',m:25,cal:5},
  {id:'golpe-de-chamas',n:'Golpe de Chamas',o:'Flame Strike',c:5,s:'Evocação',m:25,cal:5},
  {id:'ordem',n:'Ordem',o:'Geas',c:5,s:'Encantamento',m:25,cal:5},
  {id:'restaurao-superior',n:'Restauração Superior',o:'Greater Restoration',c:5,s:'Abjuração',m:25,cal:5},
  {id:'consagrar',n:'Consagrar',o:'Hallow',c:5,s:'Abjuração',m:25,cal:5},
  {id:'imobilizar-monstro',n:'Imobilizar Monstro',o:'Hold Monster',c:5,s:'Encantamento',m:25,cal:5},
  {id:'praga-de-insetos',n:'Praga de Insetos',o:'Insect Plague',c:5,s:'Conjuração',m:25,cal:5},
  {id:'lenda',n:'Lenda',o:'Legend Lore',c:5,s:'Adivinhação',m:25,cal:5},
  {id:'cura-ferimentos-em-massa',n:'Cura Ferimentos em Massa',o:'Mass Cure Wounds',c:5,s:'Abjuração',m:25,cal:5},
  {id:'despistar',n:'Despistar',o:'Mislead',c:5,s:'Ilusão',m:25,cal:5},
  {id:'modificar-memria',n:'Modificar Memória',o:'Modify Memory',c:5,s:'Encantamento',m:25,cal:5},
  {id:'atravessar-muro',n:'Atravessar Muro',o:'Passwall',c:5,s:'Transmutação',m:25,cal:5},
  {id:'vnculo-planar',n:'Vínculo Planar',o:'Planar Binding',c:5,s:'Abjuração',m:25,cal:5},
  {id:'reviver-mortos',n:'Reviver Mortos',o:'Raise Dead',c:5,s:'Necromancia',m:25,cal:5},
  {id:'reencarnao',n:'Reencarnação',o:'Reincarnate',c:5,s:'Necromancia',m:25,cal:5},
  {id:'vidncia',n:'Vidência',o:'Scrying',c:5,s:'Adivinhação',m:25,cal:5},
  {id:'aparncia',n:'Aparência',o:'Seeming',c:5,s:'Ilusão',m:25,cal:5},
  {id:'summon-dragon',n:'Summon Dragon',o:'Summon Dragon',c:5,s:'Conjuração',m:25,cal:5},
  {id:'telecinesia',n:'Telecinesia',o:'Telekinesis',c:5,s:'Transmutação',m:25,cal:5},
  {id:'telepathic-bond',n:'Telepathic Bond',o:'Telepathic Bond',c:5,s:'Adivinhação',m:25,cal:5},
  {id:'crculo-de-teleporte',n:'Círculo de Teleporte',o:'Teleportation Circle',c:5,s:'Conjuração',m:25,cal:5},
  {id:'passo-por-rvores',n:'Passo por Árvores',o:'Tree Stride',c:5,s:'Conjuração',m:25,cal:5},
  {id:'muralha-de-fora',n:'Muralha de Força',o:'Wall of Force',c:5,s:'Evocação',m:25,cal:5},
  {id:'muralha-de-pedra',n:'Muralha de Pedra',o:'Wall of Stone',c:5,s:'Evocação',m:25,cal:5},
  {id:'barreira-de-lminas',n:'Barreira de Lâminas',o:'Blade Barrier',c:6,s:'Evocação',m:30,cal:6},
  {id:'corrente-de-relmpagos',n:'Corrente de Relâmpagos',o:'Chain Lightning',c:6,s:'Evocação',m:30,cal:6},
  {id:'crculo-de-morte',n:'Círculo de Morte',o:'Circle of Death',c:6,s:'Necromancia',m:30,cal:6},
  {id:'conjurar-fada',n:'Conjurar Fada',o:'Conjure Fey',c:6,s:'Conjuração',m:30,cal:6},
  {id:'contingncia',n:'Contingência',o:'Contingency',c:6,s:'Abjuração',m:30,cal:6},
  {id:'create-undead',n:'Create Undead',o:'Create Undead',c:6,s:'Necromancia',m:30,cal:6},
  {id:'desintegrar',n:'Desintegrar',o:'Disintegrate',c:6,s:'Transmutação',m:30,cal:6},
  {id:'olhar-amedrontador',n:'Olhar Amedrontador',o:'Eyebite',c:6,s:'Necromancia',m:30,cal:6},
  {id:'find-the-path',n:'Find the Path',o:'Find the Path',c:6,s:'Adivinhação',m:30,cal:6},
  {id:'flesh-to-stone',n:'Flesh to Stone',o:'Flesh to Stone',c:6,s:'Transmutação',m:30,cal:6},
  {id:'interdio',n:'Interdição',o:'Forbiddance',c:6,s:'Abjuração',m:30,cal:6},
  {id:'esfera-congelante',n:'Esfera Congelante',o:'Freezing Sphere',c:6,s:'Evocação',m:30,cal:6},
  {id:'globo-de-invulnerabilidade',n:'Globo de Invulnerabilidade',o:'Globe of Invulnerability',c:6,s:'Abjuração',m:30,cal:6},
  {id:'guardas-e-salas',n:'Guardas e Salas',o:'Guards and Wards',c:6,s:'Abjuração',m:30,cal:6},
  {id:'ferir',n:'Ferir',o:'Harm',c:6,s:'Necromancia',m:30,cal:6},
  {id:'cura',n:'Cura',o:'Heal',c:6,s:'Abjuração',m:30,cal:6},
  {id:'banquete-dos-heris',n:'Banquete dos Heróis',o:'Heroes\' Feast',c:6,s:'Conjuração',m:30,cal:6},
  {id:'convocao-instantnea',n:'Convocação Instantânea',o:'Instant Summons',c:6,s:'Conjuração',m:30,cal:6},
  {id:'irresistible-dance',n:'Irresistible Dance',o:'Irresistible Dance',c:6,s:'Encantamento',m:30,cal:6},
  {id:'vaso-mgico',n:'Vaso Mágico',o:'Magic Jar',c:6,s:'Necromancia',m:30,cal:6},
  {id:'sugesto-em-massa',n:'Sugestão em Massa',o:'Mass Suggestion',c:6,s:'Encantamento',m:30,cal:6},
  {id:'mover-terra',n:'Mover Terra',o:'Move Earth',c:6,s:'Transmutação',m:30,cal:6},
  {id:'aliado-planar',n:'Aliado Planar',o:'Planar Ally',c:6,s:'Conjuração',m:30,cal:6},
  {id:'iluso-programada',n:'Ilusão Programada',o:'Programmed Illusion',c:6,s:'Ilusão',m:30,cal:6},
  {id:'raio-solar',n:'Raio Solar',o:'Sunbeam',c:6,s:'Evocação',m:30,cal:6},
  {id:'transport-via-plants',n:'Transport via Plants',o:'Transport via Plants',c:6,s:'Conjuração',m:30,cal:6},
  {id:'viso-da-verdade',n:'Visão da Verdade',o:'True Seeing',c:6,s:'Adivinhação',m:30,cal:6},
  {id:'muralha-de-gelo',n:'Muralha de Gelo',o:'Wall of Ice',c:6,s:'Evocação',m:30,cal:6},
  {id:'muralha-de-espinhos',n:'Muralha de Espinhos',o:'Wall of Thorns',c:6,s:'Conjuração',m:30,cal:6},
  {id:'andar-no-vento',n:'Andar no Vento',o:'Wind Walk',c:6,s:'Transmutação',m:30,cal:6},
  {id:'palavra-de-retorno',n:'Palavra de Retorno',o:'Word of Recall',c:6,s:'Conjuração',m:30,cal:6},
  {id:'espada-arcana',n:'Espada Arcana',o:'Arcane Sword',c:7,s:'Evocação',m:35,cal:7},
  {id:'conjurar-celestial',n:'Conjurar Celestial',o:'Conjure Celestial',c:7,s:'Conjuração',m:35,cal:7},
  {id:'bola-de-fogo-retardada',n:'Bola de Fogo Retardada',o:'Delayed Blast Fireball',c:7,s:'Evocação',m:35,cal:7},
  {id:'palavra-divina',n:'Palavra Divina',o:'Divine Word',c:7,s:'Evocação',m:35,cal:7},
  {id:'eterealidade',n:'Eterealidade',o:'Etherealness',c:7,s:'Conjuração',m:35,cal:7},
  {id:'dedo-da-morte',n:'Dedo da Morte',o:'Finger of Death',c:7,s:'Necromancia',m:35,cal:7},
  {id:'tempestade-de-fogo',n:'Tempestade de Fogo',o:'Fire Storm',c:7,s:'Evocação',m:35,cal:7},
  {id:'gaiola-de-fora',n:'Gaiola de Força',o:'Forcecage',c:7,s:'Evocação',m:35,cal:7},
  {id:'magnificent-mansion',n:'Magnificent Mansion',o:'Magnificent Mansion',c:7,s:'Conjuração',m:35,cal:7},
  {id:'miragem-arcana',n:'Miragem Arcana',o:'Mirage Arcane',c:7,s:'Ilusão',m:35,cal:7},
  {id:'mudana-de-plano',n:'Mudança de Plano',o:'Plane Shift',c:7,s:'Conjuração',m:35,cal:7},
  {id:'jato-prismtico',n:'Jato Prismático',o:'Prismatic Spray',c:7,s:'Evocação',m:35,cal:7},
  {id:'projetar-imagem',n:'Projetar Imagem',o:'Project Image',c:7,s:'Ilusão',m:35,cal:7},
  {id:'regenerao',n:'Regeneração',o:'Regenerate',c:7,s:'Transmutação',m:35,cal:7},
  {id:'ressurreio',n:'Ressurreição',o:'Resurrection',c:7,s:'Necromancia',m:35,cal:7},
  {id:'inverter-gravidade',n:'Inverter Gravidade',o:'Reverse Gravity',c:7,s:'Transmutação',m:35,cal:7},
  {id:'isolamento',n:'Isolamento',o:'Sequester',c:7,s:'Transmutação',m:35,cal:7},
  {id:'simulacro',n:'Simulacro',o:'Simulacrum',c:7,s:'Ilusão',m:35,cal:7},
  {id:'smbolo',n:'Símbolo',o:'Symbol',c:7,s:'Abjuração',m:35,cal:7},
  {id:'teleporte',n:'Teleporte',o:'Teleport',c:7,s:'Conjuração',m:35,cal:7},
  {id:'formas-animais',n:'Formas Animais',o:'Animal Shapes',c:8,s:'Transmutação',m:40,cal:8},
  {id:'campo-antimagia',n:'Campo Antimagia',o:'Antimagic Field',c:8,s:'Abjuração',m:40,cal:8},
  {id:'antipatiasimpatia',n:'Antipatia/Simpatia',o:'Antipathy/Sympathy',c:8,s:'Encantamento',m:40,cal:8},
  {id:'confuso',n:'Confusão',o:'Befuddlement',c:8,s:'Encantamento',m:40,cal:8},
  {id:'clone',n:'Clone',o:'Clone',c:8,s:'Necromancia',m:40,cal:8},
  {id:'controlar-clima',n:'Controlar Clima',o:'Control Weather',c:8,s:'Transmutação',m:40,cal:8},
  {id:'semiplano',n:'Semiplano',o:'Demiplane',c:8,s:'Conjuração',m:40,cal:8},
  {id:'dominar-monstro',n:'Dominar Monstro',o:'Dominate Monster',c:8,s:'Encantamento',m:40,cal:8},
  {id:'terremoto',n:'Terremoto',o:'Earthquake',c:8,s:'Transmutação',m:40,cal:8},
  {id:'lbia',n:'Lábia',o:'Glibness',c:8,s:'Encantamento',m:40,cal:8},
  {id:'aura-sagrada',n:'Aura Sagrada',o:'Holy Aura',c:8,s:'Abjuração',m:40,cal:8},
  {id:'nuvem-incendiria',n:'Nuvem Incendiária',o:'Incendiary Cloud',c:8,s:'Conjuração',m:40,cal:8},
  {id:'labirinto',n:'Labirinto',o:'Maze',c:8,s:'Conjuração',m:40,cal:8},
  {id:'mente-vazia',n:'Mente Vazia',o:'Mind Blank',c:8,s:'Abjuração',m:40,cal:8},
  {id:'palavra-de-poder-atordoante',n:'Palavra de Poder Atordoante',o:'Power Word Stun',c:8,s:'Encantamento',m:40,cal:8},
  {id:'exploso-solar',n:'Explosão Solar',o:'Sunburst',c:8,s:'Evocação',m:40,cal:8},
  {id:'tsunami',n:'Tsunami',o:'Tsunami',c:8,s:'Conjuração',m:40,cal:8},
  {id:'projeo-astral',n:'Projeção Astral',o:'Astral Projection',c:9,s:'Necromancia',m:45,cal:9},
  {id:'premonio',n:'Premonição',o:'Foresight',c:9,s:'Adivinhação',m:45,cal:9},
  {id:'portal',n:'Portal',o:'Gate',c:9,s:'Conjuração',m:45,cal:9},
  {id:'aprisionamento',n:'Aprisionamento',o:'Imprisonment',c:9,s:'Abjuração',m:45,cal:9},
  {id:'cura-em-massa',n:'Cura em Massa',o:'Mass Heal',c:9,s:'Abjuração',m:45,cal:9},
  {id:'enxame-de-meteoros',n:'Enxame de Meteoros',o:'Meteor Swarm',c:9,s:'Evocação',m:45,cal:9},
  {id:'palavra-de-poder-curativa',n:'Palavra de Poder Curativa',o:'Power Word Heal',c:9,s:'Encantamento',m:45,cal:9},
  {id:'palavra-de-poder-matadora',n:'Palavra de Poder Matadora',o:'Power Word Kill',c:9,s:'Encantamento',m:45,cal:9},
  {id:'muralha-prismtica',n:'Muralha Prismática',o:'Prismatic Wall',c:9,s:'Abjuração',m:45,cal:9},
  {id:'mudana-de-forma',n:'Mudança de Forma',o:'Shapechange',c:9,s:'Transmutação',m:45,cal:9},
  {id:'tempestade-de-vingana',n:'Tempestade de Vingança',o:'Storm of Vengeance',c:9,s:'Conjuração',m:45,cal:9},
  {id:'parar-o-tempo',n:'Parar o Tempo',o:'Time Stop',c:9,s:'Transmutação',m:45,cal:9},
  {id:'polimorfia-verdadeira',n:'Polimorfia Verdadeira',o:'True Polymorph',c:9,s:'Transmutação',m:45,cal:9},
  {id:'ressurreio-verdadeira',n:'Ressurreição Verdadeira',o:'True Resurrection',c:9,s:'Necromancia',m:45,cal:9},
  {id:'alucinao',n:'Alucinação',o:'Weird',c:9,s:'Ilusão',m:45,cal:9},
  {id:'desejo',n:'Desejo',o:'Wish',c:9,s:'Conjuração',m:45,cal:9},
];